//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceXmlService.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class combustible_excepciones
    {
        public int id_fuel_exception { get; set; }
        public string cod_cliente { get; set; }
        public string descripcion { get; set; }
    }
}
