//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceXmlService.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuration
    {
        public int id { get; set; }
        public string path_file_no_process { get; set; }
        public string path_file_process { get; set; }
        public string path_file_error { get; set; }
        public string path_file_nocorrelativo { get; set; }
    }
}
