//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceXmlService.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class correlativosSar
    {
        public int IdCorrelativoSar { get; set; }
        public Nullable<int> locationId { get; set; }
        public string CorrelativoReferencia { get; set; }
        public Nullable<int> CorrelativoInicial { get; set; }
        public Nullable<int> CorrelativoSiguiente { get; set; }
        public Nullable<int> CorrelativoFinal { get; set; }
        public Nullable<System.DateTime> FechaVenceCAI { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public string CAI { get; set; }
        public Nullable<int> notificacion { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
