//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceXmlService.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class draft_detail_post
    {
        public int draftid_detail { get; set; }
        public Nullable<int> draftId { get; set; }
        public string ItemCode { get; set; }
        public string Quantity { get; set; }
        public string UnitPrice { get; set; }
        public string ProjectCode { get; set; }
        public string CostingCode2 { get; set; }
        public string CostingCode3 { get; set; }
    }
}
