//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceXmlService.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class draft_header_post
    {
        public int draftId { get; set; }
        public string CardCode { get; set; }
        public string docObjectCode { get; set; }
        public string docDate { get; set; }
        public Nullable<int> series { get; set; }
        public string U_RTN { get; set; }
        public string U_CONTRATO { get; set; }
        public string contract_number { get; set; }
        public string json_to_sap { get; set; }
        public Nullable<int> docEntry { get; set; }
        public Nullable<int> docEntry_factura { get; set; }
        public Nullable<int> docnum { get; set; }
        public Nullable<System.DateTime> date_processed { get; set; }
        public Nullable<bool> facturado { get; set; }
    }
}
