//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceXmlService.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class draftsOrderLines
    {
        public int invoiceLinesId { get; set; }
        public string node { get; set; }
        public string second_node { get; set; }
        public string code_value { get; set; }
        public string description { get; set; }
        public Nullable<int> line_order { get; set; }
    }
}
