//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceXmlService.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class error_log
    {
        public int idlog { get; set; }
        public Nullable<System.DateTime> date_error { get; set; }
        public string project { get; set; }
        public string method_name { get; set; }
        public string error_description { get; set; }
        public string trace_error { get; set; }
        public string file_name { get; set; }
        public string contract_number { get; set; }
        public string location_code { get; set; }
    }
}
