//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceXmlService.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hertz_Projects_DevEntities : DbContext
    {
        public Hertz_Projects_DevEntities()
            : base("name=Hertz_Projects_DevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<api_configuration> api_configuration { get; set; }
        public virtual DbSet<configuration> configuration { get; set; }
        public virtual DbSet<correlatives> correlatives { get; set; }
        public virtual DbSet<correlativosSar> correlativosSar { get; set; }
        public virtual DbSet<customer_exception> customer_exception { get; set; }
        public virtual DbSet<customer_exception_for_draft> customer_exception_for_draft { get; set; }
        public virtual DbSet<draft_detail_post> draft_detail_post { get; set; }
        public virtual DbSet<draft_header_post> draft_header_post { get; set; }
        public virtual DbSet<draftsOrderLines> draftsOrderLines { get; set; }
        public virtual DbSet<error_log> error_log { get; set; }
        public virtual DbSet<invoice_error_log> invoice_error_log { get; set; }
        public virtual DbSet<locations> locations { get; set; }
        public virtual DbSet<user_credential_windows> user_credential_windows { get; set; }
        public virtual DbSet<invoice_detail_post> invoice_detail_post { get; set; }
        public virtual DbSet<invoice_header_post> invoice_header_post { get; set; }
        public virtual DbSet<combustible_excepciones> combustible_excepciones { get; set; }
    }
}
