//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceXmlService.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_header_post
    {
        public int InvoiceId { get; set; }
        public string user_SSAI { get; set; }
        public string CardCode { get; set; }
        public string docObjectCode { get; set; }
        public string docDate { get; set; }
        public Nullable<int> series { get; set; }
        public string U_RTN { get; set; }
        public string U_CONTRATO { get; set; }
        public string contract_number { get; set; }
        public string json_to_sap { get; set; }
        public Nullable<int> docEntry { get; set; }
        public Nullable<int> docnum { get; set; }
        public Nullable<System.DateTime> date_processed { get; set; }
        public Nullable<int> correlativoSar { get; set; }
        public string n_factura { get; set; }
        public string cai { get; set; }
        public string correlativoOrdenCompraExenta { get; set; }
        public string correlativoConstanciaRegistro { get; set; }
        public string identificativoRegistroSag { get; set; }
        public Nullable<decimal> granTotal { get; set; }
        public Nullable<bool> impreso { get; set; }
        public Nullable<int> id_attachment { get; set; }
        public string CANCELED { get; set; }
        public string user_anula { get; set; }
        public string actualizada_por { get; set; }
        public Nullable<bool> adicion { get; set; }
        public Nullable<bool> puede_adicionar { get; set; }
    }
}
