//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceXmlService.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_credential_windows
    {
        public int id { get; set; }
        public string user_credential { get; set; }
        public string password_credential { get; set; }
        public string ip { get; set; }
    }
}
